// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC04ipSd_K3WYImHDT01f9nROcbw7wdWxs',
    appId: '1:962503152087:web:1f8915200edcd8aa51fb92',
    messagingSenderId: '962503152087',
    projectId: 'my-portfolio-9faf3',
    authDomain: 'my-portfolio-9faf3.firebaseapp.com',
    storageBucket: 'my-portfolio-9faf3.firebasestorage.app',
    measurementId: 'G-PH66ETPLEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7u56umd_EN1ZTagZ9mJlbV8yejZePkN0',
    appId: '1:962503152087:android:3ae9b2320c65ce3751fb92',
    messagingSenderId: '962503152087',
    projectId: 'my-portfolio-9faf3',
    storageBucket: 'my-portfolio-9faf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwk6rFQTWYcs-crOGB916EYkLKTx_BN0E',
    appId: '1:962503152087:ios:060e285970db534051fb92',
    messagingSenderId: '962503152087',
    projectId: 'my-portfolio-9faf3',
    storageBucket: 'my-portfolio-9faf3.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwk6rFQTWYcs-crOGB916EYkLKTx_BN0E',
    appId: '1:962503152087:ios:060e285970db534051fb92',
    messagingSenderId: '962503152087',
    projectId: 'my-portfolio-9faf3',
    storageBucket: 'my-portfolio-9faf3.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC04ipSd_K3WYImHDT01f9nROcbw7wdWxs',
    appId: '1:962503152087:web:b86cf6ba2d88f73751fb92',
    messagingSenderId: '962503152087',
    projectId: 'my-portfolio-9faf3',
    authDomain: 'my-portfolio-9faf3.firebaseapp.com',
    storageBucket: 'my-portfolio-9faf3.firebasestorage.app',
    measurementId: 'G-LDQJ36SZEP',
  );
}
